apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "java-microservice.fullname" . }}
  labels:
    app: {{ include "java-microservice.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "java-microservice.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "java-microservice.name" . }}

    spec:

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ include "java-microservice.name" . }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.container.port }}

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                    fieldPath: metadata.name

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.container.port }}
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.container.port }}
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 10

          resources:
{{ toYaml .Values.resources | indent 12 }}
