replicaCount: 1

image:
  repository: ghcr.io/juansebastian-br/java-microservice
  tag: 255387c
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

container:
  port: 8080

env:
  SPRING_PROFILES_ACTIVE: dev

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: false


