replicaCount: 1

image:
  tag: 172f76d

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

env:
  SPRING_PROFILES_ACTIVE: dev

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 384Mi


