name: CI/CD Trunk Based

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: java-microservice
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  validate:
    if: |
      github.event_name == 'pull_request' ||
      !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        run: mvn clean package

      - name: Docker login
        if: github.event_name == 'push'
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        if: github.event_name == 'push'
        run: docker build -t $REGISTRY/$OWNER/$IMAGE_NAME:${IMAGE_TAG} .

      - name: Push Docker image
        if: github.event_name == 'push'
        run: docker push $REGISTRY/$OWNER/$IMAGE_NAME:${IMAGE_TAG}

      - name: Update Helm image tag
        if: github.event_name == 'push'
        run: |
          sed -i "s/tag: .*/tag: ${IMAGE_TAG}/" helm/java-microservice/values.yaml

      - name: Commit updated Helm values
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/java-microservice/values.yaml
          git commit -m "[skip ci] Update image tag to ${IMAGE_TAG}" || echo "No changes"
          git pull --rebase origin main
          git push
